const OK_STATUS_CODE = 200;
const HTTP_CREATED_STATUS_CODE = 201;
const INTERNAL_SERVER_ERROR_STATUS_CODE = 500;

module.exports = {
  OK_STATUS_CODE,
  HTTP_CREATED_STATUS_CODE,
  INTERNAL_SERVER_ERROR_STATUS_CODE,
};
